Get JRE 8 release packages

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -26,19 +26,19 @@ jobs:
       with:
         java-version: 1.8
 
-    - name: Build latest GL4ES
-      continue-on-error: true
-      run: |
-        cd gl4es
-        git remote add upstream https://github.com/ptitSeb/gl4es
-        git fetch upstream
-        git checkout master
-        git merge upstream/main || echo "Merge exit code $?"
-        export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
-        $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_DEBUG=1
-        cp -R libs/* ../app_pojavlauncher/src/main/jniLibs/
+#    - name: Build latest GL4ES
+#      continue-on-error: true
+#      run: |
+#        cd gl4es
+#        git remote add upstream https://github.com/ptitSeb/gl4es
+#        git fetch upstream
+#        git checkout master
+#        git merge upstream/main || echo "Merge exit code $?"
+#        export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
+#        $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_DEBUG=1
+#        cp -R libs/* ../app_pojavlauncher/src/main/jniLibs/
     
-    - name: Get JRE 8 tarballs
+    - name: Get jre8-aarch32
       uses: dawidd6/action-download-artifact@v2
       with:
             github_token: ${{secrets.GITHUB_TOKEN}}
@@ -46,6 +46,37 @@ jobs:
             path: jre
             workflow_conclusion: success
             repo: PojavLauncherTeam/android-openjdk-build-multiarch
+            name: jre8-aarch32
+            
+    - name: Get jre8-aarch64
+      uses: dawidd6/action-download-artifact@v2
+      with:
+            github_token: ${{secrets.GITHUB_TOKEN}}
+            workflow: build.yml
+            path: jre
+            workflow_conclusion: success
+            repo: PojavLauncherTeam/android-openjdk-build-multiarch
+            name: jre8-aarch64
+    
+    - name: Get jre8-x86
+      uses: dawidd6/action-download-artifact@v2
+      with:
+            github_token: ${{secrets.GITHUB_TOKEN}}
+            workflow: build.yml
+            path: jre
+            workflow_conclusion: success
+            repo: PojavLauncherTeam/android-openjdk-build-multiarch
+            name: jre8-x86
+    
+    - name: Get jre8-x86_64
+      uses: dawidd6/action-download-artifact@v2
+      with:
+            github_token: ${{secrets.GITHUB_TOKEN}}
+            workflow: build.yml
+            path: jre
+            workflow_conclusion: success
+            repo: PojavLauncherTeam/android-openjdk-build-multiarch
+            name: jre8-x86_64
     
     - name: Repack JRE
       run: |
