Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -40,24 +40,18 @@ jobs:
       if: steps.gl4es-cache.outputs.cache-hit != 'true'
       run: |
         cd gl4es
-        # git config --global user.email "PojavLauncherTeam@users.noreply.github.com"
-        # git config --global user.name "PojavLauncherTeam"
+        git config --global user.email "PojavLauncherTeam@users.noreply.github.com"
+        git config --global user.name "PojavLauncherTeam"
         git remote add upstream https://github.com/ptitSeb/gl4es
         git fetch upstream
         git checkout master
-        git merge --allow-unrelated-histories upstream/master || echo "Merge exit code $?"
+        git merge --allow-unrelated-histories upstream/master 
+        # || echo "Merge exit code $?"
         $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk
     
     - name: Install gl4es
       run: |
         cp -R gl4es/libs/* app_pojavlauncher/src/main/jniLibs/
-    
-    - name: Cache gl4es
-      uses: actions/cache@v2
-      id: gl4es-cache
-      with:
-        path: gl4es/libs
-        key: gl4es-android-shared-nodbg-test3-${{ steps.gl4es-sha.outputs.sha }}
     
     - name: Push gl4es binaries to the repository
       run: |
@@ -65,6 +59,14 @@ jobs:
         git add .
         git commit -am "CI: Update gl4es"
         git push
+        mv ../gl4es .
+    
+    - name: Cache gl4es
+      uses: actions/cache@v2
+      id: gl4es-cache
+      with:
+        path: gl4es/libs
+        key: gl4es-android-shared-nodbg-test4-${{ steps.gl4es-sha.outputs.sha }}
     
     - name: Get JRE8
       uses: dawidd6/action-download-artifact@v2
